/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReservationId = IDL.Text;
export const Time = IDL.Int;
export const PersonalInfo = IDL.Record({
  'guestName' : IDL.Text,
  'email' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const ReservationDetails = IDL.Record({
  'specialRequests' : IDL.Opt(IDL.Text),
  'submittedAt' : Time,
  'preferredTime' : IDL.Text,
  'personalInfo' : PersonalInfo,
  'numberOfGuests' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllReservations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ReservationId, ReservationDetails))],
      ['query'],
    ),
  'getReservation' : IDL.Func([ReservationId], [ReservationDetails], ['query']),
  'submitReservation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [ReservationId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReservationId = IDL.Text;
  const Time = IDL.Int;
  const PersonalInfo = IDL.Record({
    'guestName' : IDL.Text,
    'email' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const ReservationDetails = IDL.Record({
    'specialRequests' : IDL.Opt(IDL.Text),
    'submittedAt' : Time,
    'preferredTime' : IDL.Text,
    'personalInfo' : PersonalInfo,
    'numberOfGuests' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllReservations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ReservationId, ReservationDetails))],
        ['query'],
      ),
    'getReservation' : IDL.Func(
        [ReservationId],
        [ReservationDetails],
        ['query'],
      ),
    'submitReservation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [ReservationId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };