/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PersonalInfo {
  'guestName' : string,
  'email' : string,
  'phoneNumber' : string,
}
export interface ReservationDetails {
  'specialRequests' : [] | [string],
  'submittedAt' : Time,
  'preferredTime' : string,
  'personalInfo' : PersonalInfo,
  'numberOfGuests' : bigint,
}
export type ReservationId = string;
export type Time = bigint;
export interface _SERVICE {
  'getAllReservations' : ActorMethod<
    [],
    Array<[ReservationId, ReservationDetails]>
  >,
  'getReservation' : ActorMethod<[ReservationId], ReservationDetails>,
  'submitReservation' : ActorMethod<
    [string, string, string, bigint, string, [] | [string]],
    ReservationId
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];